DOMAINS = [
    "google.com",
    "google.co.in",
    "google.co.uk",
    "wikipedia.org",
    "reddit.com",
    "youtube.com",
    "x.com",
    "instagram.com",
    "facebook.com",
    "linkedin.com",
    "github.com",
    "stackoverflow.com",
    "medium.com",
    "quora.com",
    "bing.com",
    "yahoo.com",
    "amazon.com",
    "microsoft.com",
    "apple.com",
    "bbc.com",
    "nytimes.com",
    "reuters.com",
    "openai.com",
    "chatgpt.com",
    "anthropic.com",
    "claude.ai",
    "deepseek.com",
    "deepseek.ai",
    "luma.ai",
    "mistral.ai",
    "x.ai",
    "grok.com",
    "character.ai",
    "poe.com",
    "you.com",
    "phind.com",
    "pi.ai",
    "kagi.com",
    "deepmind.com",
    "gemini.google.com",
    "huggingface.co",
    "replicate.com",
    "together.ai",
    "fireworks.ai",
    "anyscale.com",
    "cohere.com",
    "perplexity.ai",
    "stability.ai",
    "midjourney.com",
    "leonardo.ai",
    "ideogram.ai",
    "suno.com",
    "udio.com",
    "elevenlabs.io",
    "heygen.com",
    "synthesia.io",
    "runwayml.com",
    "n8n.io",
    "whatsapp.com",
    "brave.com",
    "nvidia.com"
]

DEFAULT_MAX_PAGES = 200
DEFAULT_MAX_DEPTH = 2
DEFAULT_AUTO_INDEX_ENABLED = True
DEFAULT_AUTO_INDEX_INTERVAL_MINUTES = 30
DEFAULT_AUTO_INDEX_STALE_HOURS = 12
USER_AGENT = "NalandaSearchBot/0.1"
